language: php
php:
  - 5.3
  - 5.4

env:
  - DB=firebird
  - DB=mysql
  - DB=postgres
  - DB=sqlite

matrix:
  allow_failures:
    - env: DB=firebird
    - env: DB=sqlite

after_install:
  - if [[ "$DB" == "firebird" ]]; then sudo service firebird2.5-super start; fi
  - if [[ "$DB" == "firebird" ]]; then ./scripts/python/firebird_init.py; fi

before_script:
  - if [[ "$DB" == "firebird" ]]; then echo 'CREATE DATABASE "localhost:/tmp/stk_tests.fdb" PAGE_SIZE = 16384;' > /tmp/create.sql; fi
  - if [[ "$DB" == "firebird" ]]; then isql-fb -u SYSDBA -p masterkey -i /tmp/create.sql -q; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS stk_tests;" -uroot; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS stk_tests;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database stk_tests;" -U postgres; fi
  - pyrus install phpunit/DbUnit
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - ./scripts/python/vendor.py -f -s

script:
  - phpcs -p -s --report-full --report-gitblame --standard=codesniffer stk/
  - phpunit --configuration test/travis/$DB.travis.xml

notifications:
  email:
    recipients:
      - erikfrerejean@phpbb.com
    on_success: always
    on_faillure: always

# branches:
#  only:
#    stk/ascraeus

