language: php
php:
  - 5.3
  - 5.4

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

matrix:
  allow_failures:
    - env: DB=sqlite

before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS stk_tests;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database stk_tests;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS stk_tests;" -uroot; fi
  - pyrus install phpunit/DbUnit
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - ./scripts/python/vendor.py -f -s

script:
  - phpunit --configuration test/travis/$DB.travis.xml

after_script:
  - phpcs -p -s --report-full --report-gitblame --standard=stkcodesniffer stk/

notifications:
  email:
    recipients:
      - erikfrerejean@phpbb.com
    on_success: always
    on_faillure: always

# branches:
#  only:
#    stk/ascraeus

